const CATEGORIES_ACTION_TYPE = {
    // SET_CATEGORIES : 'SET_CATEGORIES',
    FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_FAILED',
    FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
}
export default CATEGORIES_ACTION_TYPE;